[toolchain]

[features]
seeds = false
skip-lint = false

# [programs.mainnet]
# bwb_stake = "Eqsv4KVNu7tQirC5J5jb4ZT1gSbjUiksSye8oZyFsVc4"
[programs.devnet]
bwb_stake = "Eqsv4KVNu7tQirC5J5jb4ZT1gSbjUiksSye8oZyFsVc4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/xp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
